version: '3.7'
services:
 mysql:
  build: ./mysql/
  cap_add:
      - SYS_NICE
  container_name: Full2020-86303
  restart: always
  environment:
   MYSQL_DATABASE: AdamJ
   MYSQL_USER: AJarszak
   MYSQL_PASSWORD: AJarszak
   MYSQL_ROOT_PASSWORD: AJarszak
  ports:
   - 3306:3306
  networks:
   second:
      ipv4_address: 172.16.238.22

 java:
  image: adam1000a1/lab_java
  container_name: lab_java_container
  depends_on:
   - mysql
  networks:
   - second
  stdin_open: true
  tty: true


volumes:
  db-data:

networks:
 second:
  driver: bridge
  ipam:
   config:
    - subnet: 172.16.238.0/24
